// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Advertisment
{
    public int Id { get; set; }

    public string AdvertName { get; set; } = null!;

    public string? Mediatype { get; set; }

    public string? MediaFile { get; set; }

    public virtual ICollection<DisplayAdverts> DisplayAdverts { get; set; } = new List<DisplayAdverts>();
}