// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class BookingSettingOrg
{
    public int Id { get; set; }

    public TimeSpan? StartWorkingHour { get; set; }

    public TimeSpan? EndWorkingHour { get; set; }

    public int? OrgId { get; set; }

    public TimeSpan? KioskClosingTime { get; set; }

    public int? UserlimitReservation { get; set; }

    public virtual Organization? Org { get; set; }
}