// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Citizen
{
    public int CitizenId { get; set; }

    public string? Name { get; set; }

    public string Nid { get; set; } = null!;

    public string Mobile { get; set; } = null!;

    public bool Sex { get; set; }

    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();

    public virtual ICollection<Reservations> Reservations { get; set; } = new List<Reservations>();
}