// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class CounterServices
{
    public int Id { get; set; }

    public int? CounterId { get; set; }

    public int? ServiceId { get; set; }

    public virtual Counters? Counter { get; set; }

    public virtual Service? Service { get; set; }
}