// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public int? Citizenid { get; set; }

    public virtual Citizen? Citizen { get; set; }

    public virtual ICollection<Reservations> Reservations { get; set; } = new List<Reservations>();
}