// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Display
{
    public int DisplayId { get; set; }

    public string DisplayName { get; set; } = null!;

    public int? Orgid { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<DisplayAdverts> DisplayAdverts { get; set; } = new List<DisplayAdverts>();

    public virtual ICollection<DisplayCounters> DisplayCounters { get; set; } = new List<DisplayCounters>();

    public virtual Organization? Org { get; set; }
}