// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class DisplayAdverts
{
    public int Id { get; set; }

    public int AdvertId { get; set; }

    public int DisplayId { get; set; }

    public virtual Advertisment Advert { get; set; } = null!;

    public virtual Display Display { get; set; } = null!;
}