// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class DisplayCounters
{
    public int? DisplayId { get; set; }

    public int? CounterId { get; set; }

    public int Id { get; set; }

    public virtual Counters? Counter { get; set; }

    public virtual Display? Display { get; set; }
}