// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public int? Citizenid { get; set; }

    public int? Orgid { get; set; }
    public bool? IsActive { get; set; }

    public virtual Citizen? Citizen { get; set; }

    public virtual ICollection<Counters> Counter { get; set; } = new List<Counters>();

    public virtual ICollection<GroupUser> GroupUser { get; set; } = new List<GroupUser>();

    public virtual Organization? Org { get; set; }
}