// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class GroupUser
{
    public int Id { get; set; }

    public int EmpId { get; set; }

    public int GroupId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Employee Emp { get; set; } = null!;

    public virtual Group Group { get; set; } = null!;
}