// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace Models.Models;

public partial class Reservations
{
    public long Id { get; set; }

    public string? Nid { get; set; } 

    public DateTime ReservationDate { get; set; }

    public string? Name { get; set; }

    public double? QueueSerial { get; set; }

    public bool? IsCancelled { get; set; }

    public int? CitizenId { get; set; }

    public int? CustomerId { get; set; }

    public string? Status { get; set; }

    public int? CounterId { get; set; }

    public string? MobileNumber { get; set; }

    public string? TicketNumber { get; set; }

    public double? ReqId { get; set; }

    public DateTime? CallAt { get; set; }

    public DateTime EndServing { get; set; }

    public string? ReservationType { get; set; }

    public int? Orgid { get; set; }
    public int? ServiceId { get; set; }

    public virtual Citizen Citizen { get; set; } = null!;

    public virtual Customer Customer { get; set; } = null!;


    public virtual Service? Service { get; set; }

    public virtual Organization? Org { get; set; }
    public virtual ICollection<ServiceReservation> ReservationsServices { get; set; } = new List<ServiceReservation>();
}